=== danielbarion/JBlueHeart-Source/L2J_SunriseProject_Data/dist/game/data/xsd/pcBreathBonus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="pcBreathBonus">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="breathBonus" minOccurs="1" maxOccurs="20">
					<xs:complexType>
						<xs:attribute name="classId" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:nonNegativeInteger">
									<xs:enumeration value="0" />
									<xs:enumeration value="10" />
									<xs:enumeration value="18" />
									<xs:enumeration value="25" />
									<xs:enumeration value="31" />
									<xs:enumeration value="38" />
									<xs:enumeration value="44" />
									<xs:enumeration value="49" />
									<xs:enumeration value="53" />
									<xs:enumeration value="123" />
									<xs:enumeration value="124" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="sex" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="female" />
									<xs:enumeration value="male" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="val" type="xs:nonNegativeInteger" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== danielbarion/JBlueHeart-Source/L2J_SunriseProject_Data/dist/game/data/xml/stats/chars/pcBreathBonus.xml
<?xml version="1.0" encoding="UTF-8"?>
<pcBreathBonus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/pcBreathBonus.xsd">
	<breathBonus classId="0" sex="female" val="100" /> <!-- 100% --> <!-- Female Human Fighter -->
	<breathBonus classId="0" sex="male" val="100" /> <!-- 100% --> <!-- Male Human Fighter -->
	<breathBonus classId="10" sex="female" val="100" /> <!-- 100% --> <!-- Female Human Mystic -->
	<breathBonus classId="10" sex="male" val="100" /> <!-- 100% --> <!-- Male Human Mystic -->
	<breathBonus classId="18" sex="female" val="150" /> <!-- 150% --> <!-- Female Elven Fighter -->
	<breathBonus classId="18" sex="male" val="150" /> <!-- 150% --> <!-- Male Elven Fighter -->
	<breathBonus classId="25" sex="female" val="150" /> <!-- 150% --> <!-- Female Elven Mystic -->
	<breathBonus classId="25" sex="male" val="150" /> <!-- 150% --> <!-- Male Elven Mystic -->
	<breathBonus classId="31" sex="female" val="150" /> <!-- 150% --> <!-- Female Dark Fighter -->
	<breathBonus classId="31" sex="male" val="150" /> <!-- 150% --> <!-- Male Dark Fighter -->
	<breathBonus classId="38" sex="female" val="150" /> <!-- 150% --> <!-- Female Dark Mystic -->
	<breathBonus classId="38" sex="male" val="150" /> <!-- 150% --> <!-- Male Dark Mystic -->
	<breathBonus classId="44" sex="female" val="90" /> <!-- 90% --> <!-- Female Orc Fighter -->
	<breathBonus classId="44" sex="male" val="90" /> <!-- 90% --> <!-- Male Orc Fighter -->
	<breathBonus classId="49" sex="female" val="90" /> <!-- 90% --> <!-- Female Orc Mystic -->
	<breathBonus classId="49" sex="male" val="90" /> <!-- 90% --> <!-- Male Orc Mystic -->
	<breathBonus classId="53" sex="female" val="80" /> <!-- 80% --> <!-- Female Dwarven Fighter -->
	<breathBonus classId="53" sex="male" val="80" /> <!-- 80% --> <!-- Male Dwarven Fighter -->
	<breathBonus classId="124" sex="female" val="100" /> <!-- 100% --> <!-- Female Soldier -->
	<breathBonus classId="123" sex="male" val="100" /> <!-- 100% --> <!-- Male Male Soldier -->
</pcBreathBonus>
